### PR TITLE
Timeout

### LINKED ISSUE #5: Timeout accesses to external services
Blocking calls that access external services (currently ipinfo.io) must have a timeout so callers are not indefinitely locked.

This issue is a request for having timeouts implemented when the library reaches external services.

### PR DESCRIPTION
**Pull request by coolparadox**
@sajal The _timeout_ branch was created on top of _static_ip_test_ branch, so there are common commits at the beginning.

Fixes #5

### CODE REVIEW

**Comment by coolparadox** [comment]
As a side note, I could not find a quick solution for testing the timeout parameter. Should we open an issue for investigating a way of testing the library with delayed network access?

**Comment by sajal** [comment]
Yes make an issue for for it. We can circle back to it when figuring out http timing tests for CNC

**Comment by sajal** [comment]
`func NewHandler(timeoutMS int64) (Handler, error)`

Whenever accepting such input, please use type `time.Duration` . That way user can express it however they want instead of being forced to think in milliseconds.

**Comment by coolparadox** [comment]
Created #12 for testing timeouts

**Comment by coolparadox** [comment]
@sajal Back using time.Duration in NewHandler().

Moreover, when a value zero is passed as timeout, it now means "no timeout", as it's the default behaviour for http.Client and dns.Client.

**Pull request merged**
